runtime: python39

# Entry point to your app, adjust if you have a different entry file
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

# Configuration for App Engine instance settings
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5

# Environment variables (optional)
env_variables:
  APP_ENV: "production"
